<a href="https://colab.research.google.com/github/CrisGood/INTELIGENCIA-ARTIFICIAL/blob/main/TALLER2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# TALLER — Módulo 2 — Creación y Atributos de Arrays
# AUTOR CRISTIAN NARVAEZ
# FECHA 21/04/2026

# Ejercicio 1: Crea los siguientes arrays y verifica sus atributos (shape, dtype, ndim)
### a) Vector con enteros del 1 al 20.
### b) Matriz de ceros de 5 filas y 3 columnas.
### c) 10 puntos igualmente espaciados entre -1 y 1 con linspace.

In [ ]:
import numpy as np

# a) Vector con enteros del 1 al 20
vector_a = np.arange(1, 21)

# b) Matriz de ceros de 5 filas y 3 columnas
matriz_b = np.zeros((5, 3))

# c) 10 puntos igualmente espaciados entre -1 y 1
linspace_c = np.linspace(-1, 1, 10)

# Verificación de atributos
arrays = [("Vector A", vector_a), ("Matriz B", matriz_b), ("Linspace C", linspace_c)]

for nombre, arr in arrays:
    print(f"--- {nombre} ---")
    print(f"Shape (Forma): {arr.shape}")
    print(f"Dtype (Tipo):  {arr.dtype}")
    print(f"Ndim (Ejes):   {arr.ndim}")
    print()

--- Vector A ---
Shape (Forma): (20,)
Dtype (Tipo):  int64
Ndim (Ejes):   1

--- Matriz B ---
Shape (Forma): (5, 3)
Dtype (Tipo):  float64
Ndim (Ejes):   2

--- Linspace C ---
Shape (Forma): (10,)
Dtype (Tipo):  float64
Ndim (Ejes):   1



#Ejercicio 2: Con np.random.seed(99) crea una matriz 4×4 de enteros entre 0 y 50

###Imprime: shape, dtype, tamaño en bytes (nbytes) y el elemento [2,3].

In [ ]:
import numpy as np

# 1. Establecemos la semilla para que el resultado sea reproducible
np.random.seed(99)

# 2. Creamos la matriz 4x4 con enteros entre 0 y 50 (el 51 es exclusivo)
matriz = np.random.randint(0, 51, (4, 4))

# 3. Impresión de resultados y atributos
print("Matriz generada:")
print(matriz)
print("-" * 30)
print(f"Shape (Forma):       {matriz.shape}")
print(f"Dtype (Tipo de dato): {matriz.dtype}")
print(f"Tamaño en bytes:     {matriz.nbytes} bytes")
print(f"Elemento en [2,3]:   {matriz[2, 3]}")

Matriz generada:
[[ 1 35 40  9]
 [40 18  4  5]
 [ 1 23 35 49]
 [ 1 48 29 38]]
------------------------------
Shape (Forma):       (4, 4)
Dtype (Tipo de dato): int64
Tamaño en bytes:     128 bytes
Elemento en [2,3]:   49


#Ejercicio 3: ¿Cuál es la diferencia de dtype entre np.array([1,2,3]) y
###np.array([1.0,2.0,3.0])? Verifica con código.

In [ ]:
import numpy as np

# Creamos ambos arrays
arr_int = np.array([1, 2, 3])
arr_float = np.array([1.0, 2.0, 3.0])

# Verificamos sus tipos de datos (dtype)
print(f"Dtype de [1, 2, 3]:   {arr_int.dtype}")
print(f"Dtype de [1.0, 2.0, 3.0]: {arr_float.dtype}")

Dtype de [1, 2, 3]:   int64
Dtype de [1.0, 2.0, 3.0]: float64


NOTA DEL EJERCICIO: int64 (o int32): El primer array contiene números enteros. NumPy detecta que no hay decimales y asigna un tipo de dato entero, lo cual ahorra espacio en memoria y es ideal para índices o recuentos.

float64: El segundo array, al incluir el punto decimal (.0), fuerza a NumPy a utilizar punto flotante. Esto permite realizar cálculos científicos precisos, pero ocupa más bits por elemento.

#Ejercicio 4: Crea una matriz identidad 5×5 y verifica que la suma de su diagonal
###es igual a 5 (usa np.trace()).

In [1]:
import numpy as np

# Crear la matriz identidad 5x5
matriz = np.eye(5)

print("Matriz identidad:")
print(matriz)

# Calcular la suma de la diagonal
suma_diagonal = np.trace(matriz)

print("Suma de la diagonal:", suma_diagonal)

# Verificación
if suma_diagonal == 5:
    print("Verificación correcta: la suma es 5")
else:
    print("Algo salió mal")

Matriz identidad:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Suma de la diagonal: 5.0
Verificación correcta: la suma es 5
