<a href="https://colab.research.google.com/github/CrisGood/INTELIGENCIA-ARTIFICIAL/blob/main/TALLER3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



---

# PRÁCTICA — Módulo 3 — Indexing, Slicing, Reshape
# AUTOR CRISTIAN NARVAEZ
# FECHA 21/04/2026

###Ejercicio 1: Dado A = np.arange(1, 26).reshape(5, 5)
###a) Extrae la sub-matriz de las 3 últimas filas y las 3 primeras columnas.
###b) Extrae la segunda columna completa.
###c) Extrae los elementos de los ángulos (esquinas) de la matriz.

In [ ]:
import numpy as np

A = np.arange(1, 26).reshape(5, 5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


###a) Extrae la sub-matriz de las 3 últimas filas y las 3 primeras columnas.


In [ ]:
sub = A[-3:, :3]
print(sub)

[[11 12 13]
 [16 17 18]
 [21 22 23]]


###b) Extrae la segunda columna completa

In [ ]:
col = A[:, 1]
print(col)

[ 2  7 12 17 22]


###c) Extrae los elementos de los ángulos (esquinas) de la matriz.

In [ ]:
corners = [A[0,0], A[0,-1], A[-1,0], A[-1,-1]]
print(corners)

[np.int64(1), np.int64(5), np.int64(21), np.int64(25)]


###Ejercicio 2: Con la misma matriz A:
###a) Crea una máscara booleana para los valores mayores a 12.
###b) Reemplaza esos valores por -1 en una copia del array.
###c) Usa np.where para reemplazar impares por 0 y mantener los pares.

In [ ]:
mask = A > 12
print(mask)

[[False False False False False]
 [False False False False False]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


###b) Reemplaza esos valores por -1 en una copia del array.

In [ ]:
B = A.copy()
B[mask] = -1
print(B)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


###c) Usa np.where para reemplazar impares por 0 y mantener los pares.

In [ ]:
C = np.where(A % 2 == 0, A, 0)
print(C)

[[ 0  2  0  4  0]
 [ 6  0  8  0 10]
 [ 0 12  0 14  0]
 [16  0 18  0 20]
 [ 0 22  0 24  0]]


###Ejercicio 3: Crea un vector de 24 elementos con arange(24).
###Reorganízalo en: (a) matriz 6×4, (b) tensor 2×3×4, (c) vector fila 1×24

In [ ]:
v = np.arange(24)

(a) matriz 6×4

In [ ]:
m1 = v.reshape(6, 4)
print(m1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


###(b) tensor 2×3×4

In [ ]:
t = v.reshape(2, 3, 4)
print(t)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


###(c) vector fila 1×24

In [ ]:
row = v.reshape(1, 24)
print(row)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]


###Ejercicio 4: Demuestra la diferencia vista vs. copia: modifica un elemento
###en un slice y verifica que el array original también cambia.

In [ ]:
A = np.arange(1, 10).reshape(3, 3)

slice_view = A[:2, :2]  # esto es una VISTA
slice_view[0, 0] = 999

print("Slice modificado:")
print(slice_view)

print("Array original:")
print(A)

Slice modificado:
[[999   2]
 [  4   5]]
Array original:
[[999   2   3]
 [  4   5   6]
 [  7   8   9]]
